version: '3.1'
services:
  api:
    environment:
      HTTP_PORT: 80
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:80
      - 5858:5858
    volumes:
      - .:/www
      - /www/node_modules
    entrypoint: '
      sh -ce "
        ./node_modules/.bin/nodemon --delay 100ms --exec \"fuser -k 5858/tcp; node --inspect=0.0.0.0:5858 ./node_modules/.bin/ts-node src/index.ts\"
      "
    '